language: python
dist: xenial

python:
 - 3.5
 - 3.6
 - 3.7
 - 3.8

env:
 - DJANGO=2.1 VARIANT=normal
 - DJANGO=2.2 VARIANT=normal
 - DJANGO=3.0 VARIANT=normal
 - DJANGO=master VARIANT=normal

matrix:
  include:
    - python: 3.5
      env: DJANGO=1.11 VARIANT=yubikey
    - python: 3.5
      env: DJANGO=1.11 VARIANT=custom_user
    - python: 3.6
      env: DJANGO=1.11 VARIANT=normal
    - python: 3.6
      env: DJANGO=1.11 VARIANT=yubikey
    - python: 3.6
      env: DJANGO=1.11 VARIANT=custom_user
    - python: 3.7
      env: DJANGO=1.11 VARIANT=normal
    - python: 3.7
      env: DJANGO=1.11 VARIANT=yubikey
    - python: 3.7
      env: DJANGO=1.11 VARIANT=custom_user

    - python: 3.5
      env: DJANGO=2.2 VARIANT=yubikey
    - python: 3.5
      env: DJANGO=2.2 VARIANT=custom_user
    - python: 3.6
      env: DJANGO=2.2 VARIANT=yubikey
    - python: 3.6
      env: DJANGO=2.2 VARIANT=custom_user
    - python: 3.7
      env: DJANGO=2.2 VARIANT=yubikey
    - python: 3.7
      env: DJANGO=2.2 VARIANT=custom_user
    - python: 3.8
      env: DJANGO=2.2 VARIANT=yubikey
    - python: 3.8
      env: DJANGO=2.2 VARIANT=custom_user

    - python: 3.6
      env: DJANGO=3.0 VARIANT=yubikey
    - python: 3.6
      env: DJANGO=3.0 VARIANT=custom_user
    - python: 3.7
      env: DJANGO=3.0 VARIANT=yubikey
    - python: 3.7
      env: DJANGO=3.0 VARIANT=custom_user
    - python: 3.8
      env: DJANGO=3.0 VARIANT=yubikey
    - python: 3.8
      env: DJANGO=3.0 VARIANT=custom_user

    - python: 3.6
      env: DJANGO=master VARIANT=yubikey
    - python: 3.6
      env: DJANGO=master VARIANT=custom_user
    - python: 3.7
      env: DJANGO=master VARIANT=yubikey
    - python: 3.7
      env: DJANGO=master VARIANT=custom_user
    - python: 3.8
      env: DJANGO=master VARIANT=yubikey
    - python: 3.8
      env: DJANGO=master VARIANT=custom_user

    - python: 3.6
      env: TOXENV=isort
    - python: 3.6
      env: TOXENV=flake8

  exclude:
    - python: 3.5
      env: DJANGO=master VARIANT=normal

  allow_failures:
    - env: DJANGO=master VARIANT=normal
    - env: DJANGO=master VARIANT=yubikey
    - env: DJANGO=master VARIANT=custom_user

install: pip install tox-travis codecov
script: tox
after_success: codecov
