language: python
python:
  - 2.6
  - 2.7
  - 3.3
env:
  - DJANGO=django==1.4.5
  - DJANGO=django==1.5.1
matrix:
  exclude:
    - python: 3.3
      env: DJANGO=django==1.4.5
install:
  - pip install $DJANGO --use-mirrors
  - pip install -r requirements.txt --use-mirrors
  # run 2to3 for Python 3.3
  - "if [[ $TRAVIS_PYTHON_VERSION == '3.3' ]]; then 2to3 -w -n --no-diffs . 2>&1 | tail -n 2; fi"
script: coverage run demo/manage.py test
after_success:
  - coverage report
