language: python
python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
env:
  - DJANGO=Django==1.4.10
  - DJANGO=Django==1.5.5
  - DJANGO=Django==1.6.2
  - DJANGO=https://www.djangoproject.com/download/1.7b1/tarball/
matrix:
  exclude:
    - python: "2.6"
      env: DJANGO=https://www.djangoproject.com/download/1.7b1/tarball/
    - python: "3.2"
      env: DJANGO=Django==1.4.10
    - python: "3.3"
      env: DJANGO=Django==1.4.10
    - python: "3.4"
      env: DJANGO=Django==1.4.10
install:
  - pip install $DJANGO
  - pip install -e .
  - pip install coveralls twilio qrcode
script: make coverage
after_success: coveralls
